### PR TITLE
set default to 15

### PR DESCRIPTION
**Pull request by msach22**
### Contributing checklist
- [x] Code must follow existing styling conventions
- [x] Added a descriptive commit message

### CODE REVIEW

**Comment by msach22** [comment]
@mark-veenstra let me know what you think!

**Comment by mark-veenstra** [comment]
@msach22 Just got back from vacation, maybe scheduling a call will help indeed.
Just changing this setting doesn't help! The problem is it does not matter wat you set on that line. The framerate wil always be wrong. So it is something within the SDK.

Have you tested this codebase with this setting as you propose? You can than also see that the setting won't do anything on Android when you open the session inspector.

**Comment by mark-veenstra** [comment]
@msach22 As I just checked through all emails the session ids shared with you shows a frameRate of 15 in your internal logs. But the bitrate is till doubled. So why is the bitrate still doubled?

**Comment by msach22** [comment]
Cherry picked and added to 3.4.0

**Pull request closed without merging**
