### PR TITLE
3.2.0

### PR DESCRIPTION
**Pull request by msach22**
*Adds browser platform support
*Updates package.json so Cordova 7 and above can use the plugin
*Adds PR and Issues template
*Adds remaining iOS and Android event emitters

### CODE REVIEW

**Comment by msach22** [comment]
@mark-veenstra @wolfenrain Can you both run this latest branch and help me test and verify that all new changes work :) ?

**Comment by mark-veenstra** [comment]
@msach22 we are running on this branch for a while and it works like a charm... We did need PR #52 to be included in our project otherwise we would have build issues since the different plugins need different support libraries.

**Comment by mark-veenstra** [comment]
resolved conflict... will do some tests with this branch

**Comment by mark-veenstra** [comment]
@msach22 from our tests sometimes a crash happens, this PR: https://github.com/opentok/cordova-plugin-opentok/pull/58 solves that on the `3.2.0` branch.

**Comment by wolfenrain** [comment]
@msach22 Another crash happens on iOS 10. This PR: #60 solves it.

**Comment by wolfenrain** [comment]
@msach22 both the #58 & #60 PRs have been put on WIP. They need further investigation.

**Comment by wolfenrain** [comment]
@msach22 Removed the WIP from #58 PR. Added a comment with some explanation. You can merge if there are no further issues.

**Comment by wolfenrain** [comment]
@msach22 Also removed the WIP from #60 PR.

**Comment by wolfenrain** [comment]
@msach22 I would suggest to merge #64 PR aswell before merging this one. Considering it is a core feature to be able to disable `publishVideo` on `initPublisher`.

**Comment by mark-veenstra** [comment]
@msach22 We have been testing the last few days and all is okay, but PR #58 and #60 are needed as fixes on the `3.2.0` branch. If they get merged in all seems fine to us to release `3.2.0`. Did you encounter any issues, if not can it be released?

**Comment by msach22** [comment]
@mark-veenstra @wolfenrain This works really well so far, going to test #55 and merge if all is good. I'm also going to remove the console.log statement for each event that's triggered mainly b/c audioLevelUpdated makes it hard to debug b/c it keeps printing the statement. Let me know what you think?

**Comment by mark-veenstra** [comment]
@msach22 yeah we removed that log also because it also slows down the app with the amount of logging.

**Comment by msach22** [comment]
@mark-veenstra awesome, I'll make those changes. One of the PR's fixed the package json mismatch issue, do you think it's better to go with `Cordova-Plugin-OpenTok` or `com.tokbox.cordova.opentok` b/c I also want to release this package on npm after the 3.2.0 release

**Comment by mark-veenstra** [comment]
@msach22 the value within the `plugin.xml` in attribute `id` should be equal to the `package.json`. So looking at those two the end result should be `com.tokbox.cordova.opentok`.

But to be honest the must plugins do have (and should have) a name beginning with `cordova-plugin-*`, so a name of `cordova-plugin- opentok` would be the best! So changing this in `package.json` and `plugin.xml` would be awesome.

**Comment by msach22** [comment]
@mark-veenstra Added the last PRs. Doing one more sanity check and will merge if all is good. Please do the same if you can :)

**Comment by mark-veenstra** [comment]
@msach22 all seems fine to me

**Comment by msach22** [comment]
@mark-veenstra same here, merging!

**Pull request merged**
