### PR TITLE
#33 - `package.json` name should be equal to the plugin id

### PR DESCRIPTION
**Pull request by mark-veenstra**
Change is needed to be able to use the plugin with Cordova >7. Solves #33

### CODE REVIEW

**Comment by mark-veenstra** [comment]
This is still a WIP

**Comment by mark-veenstra** [comment]
work is done

**Comment by msach22** [comment]
@mark-veenstra can we please resolve the merge conflicts? After that, I will merge in the PR!

**Comment by mark-veenstra** [comment]
@msach22 done

**Pull request merged**
